apiVersion: apps/v1
kind: Deployment
metadata:
  name: vitality-backend
  namespace: vitality-studio
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vitality-backend
  template:
    metadata:
      labels:
        app: vitality-backend
    spec:
      containers:
        - name: backend
          image: vitality-backend:latest
          ports:
            - containerPort: 8000
          env:
            - name: VITALITY_EXECUTOR_URL
              value: "http://vitality-execution:9000/execute"

---
apiVersion: v1
kind: Service
metadata:
  name: vitality-backend
  namespace: vitality-studio
spec:
  selector:
    app: vitality-backend
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
